blog/urls.py
from django.urls import path
from .views import blog,post_details

app_name='blog'
urlpatterns = [
    path("",blog ,name='blog'),
    path("<int:num>/",post_details ,name='post-detail'),
    path("category/<cat>/",blog ,name='category'),
    path("tag/<tag>/",blog ,name='tag'),
    path("author/<str:auth>/",blog ,name='author'),
]

core/urls.py

from django.urls import include  
from django.contrib import admin  
from django.urls import path  

from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('', include('website.urls')), 
    path('accounts/',include('accounts.urls')) ,
    path('blog/', include('blog.urls')),  
    path('captcha/', include('captcha.urls')),
]  

# Serve static files in development  
if settings.DEBUG:  
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models  
from accounts.models import CustomUser
from taggit.managers import TaggableManager

# Create your models here. 
# 
# 


class Category(models.Model):  
    title = models.CharField(max_length=150)
    def __str__(self):  
        return self.title
 

class Post(models.Model):  
    title = models.CharField(max_length=255)  
    description = models.TextField()  
    active = models.BooleanField(default=False)
    created_time = models.DateTimeField(auto_now_add=True)  
    updated_time = models.DateTimeField(auto_now=True)  
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)  
    image = models.ImageField(upload_to="blog/images/", default="blog/images/default.jpg")  
    category = models.ManyToManyField(Category)
    tags = TaggableManager()

    def __str__(self):  
        return self.title  

    class Meta:  
        verbose_name = "Post"  
        verbose_name_plural = "Posts"



class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    name=models.CharField(max_length=250)
    email=models.EmailField(max_length=254)
    subject=models.CharField(max_length=250)
    message=models.TextField()
    active = models.BooleanField(default=False)
    created_time = models.DateTimeField(auto_now_add=True)  
    updated_time = models.DateTimeField(auto_now=True)  

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_time']

blog/forms.py
from django import forms
from .models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta:
        model = Comment  
        fields = '__all__'

blog/views.py
from django.shortcuts import render, get_object_or_404  
from .models import Post  , Comment
from django.db.models import Q  
from .forms import CommentForm  
from django.shortcuts import redirect
from django.contrib import messages  
# Create your views here.  
def blog(request, **kwargs):  
    posts = Post.objects.filter(active=True)  

    if kwargs.get("cat"):  
        posts = posts.filter(category__title=kwargs["cat"])  

    if kwargs.get("auth"):  
        posts = posts.filter(author__username=kwargs["auth"])  

    if kwargs.get("tag"):  
        posts = posts.filter(tags__name=kwargs["tag"])  

    if search := request.GET.get("q"):
        posts=posts.filter(Q(title__icontains=search) | Q(description__icontains=search))


    context = {"posts": posts}  
    return render(request, "blog/blog.html", context)  



def post_details(request, num):   
    post = get_object_or_404(Post, id=num, active=True)  
    comment=Comment.objects.filter(post=post, active=True)

    if request.method=="POST":
        forms=CommentForm(request.POST)
        if forms.is_valid():
            forms.instance.post=post
            forms.save()
            messages.success(request, "Comment has been posted successfully")
            return redirect('/')


    forms=CommentForm()
    context = {"post": post,"comment":comment,"form":forms}     
    return render(request, "blog/post-details.html", context)

templates/blog/blog.html
{% extends "base.html" %} 
{%load static%}
{%load blog_tags%}
 {% block content %}
<!-- Banner Starts Here -->
<div class="heading-page header-text">
  <section class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="text-content">
            <h4>Recent Posts</h4>
            <h2>Our Recent Blog Entries</h2>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<!-- Banner Ends Here -->

<section class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="main-content">
          <div class="row">
            <div class="col-lg-8">
              <span>Stand Blog HTML5 Template</span>
              <h4>Creative HTML Template For Bloggers!</h4>
            </div>
            <div class="col-lg-4">
              <div class="main-button">
                <a
                  href="https://templatemo.com/tm-551-stand-blog"
                  target="_parent"
                  >Download Now!</a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="blog-posts grid-system">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="all-blog-posts">
          <div class="row">

            {% for post in posts %}
               <div class="col-lg-6" >
              <div class="blog-post">
                <div class="blog-thumb">
                  <img src="{{post.image.url}}" alt="">
                </div>
                <div class="down-content">
                  <span><a href="{% url 'blog:post-detail' num=post.id %}">{{post.title|lower}}</a></span>
                  {% comment %} <a href="post-details.html"><h4>Donec tincidunt leo</h4></a> {% endcomment %}
                  <ul class="post-info">
                    <li><a href="{% url "blog:author" auth=post.author%}">{{post.author|lower}}</a></li>
                    <li><a href="#">Created in: {{ post.created_time | date:"Y/m/d" }}</a></li>
                    <li><a href="#">Last Edit: {{ post.updated_time}}</a></li>
                  </ul>
                  <p>{{post.description | truncatechars:50}}</p>


                  
                  
                  <div class="post-options">
                    <div class="row">
                      <div class="col-lg-12">
                        <ul class="post-tags">
                          <li><i class="fa fa-tags">Post Categories:</i></li>
                          {% for cat in post.category.all%}
                          <li><a href="{% url "blog:category" cat=cat.title %}">{{cat.title}} ,
                             </a></li> 
                           {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                 
                  
                  <div class="post-options">
                    <div class="row">
                      <div class="col-lg-12">
                        <ul class="post-tags">
                          <li><i class="fa fa-tags">Post Tags:</i></li>
                          {% for tag in post.tags.all %}
                          <li><a href="{% url "blog:tag" tag=tag.name %}">{{tag.name}},</a></li> 
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>

                  
                </div>
              </div>
            </div>
            {% endfor %}
            
         



            <div class="col-lg-12">
              <ul class="page-numbers">
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li>
                  <a href="#"><i class="fa fa-angle-double-right"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="sidebar">
          <div class="row">

      {% include "blog/includes/blog-search.html" %} 
      {% recent_post %} 
      {% categories %} 
      {% include "blog/includes/blog-tags.html" %} 
      {% comment %} {% test 'ali' %} {% endcomment %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock %}

templates/blog/post-details.html
{% extends "base.html" %}
{%load static%}
{%load blog_tags%}
{% block content %}
    <!-- Banner Starts Here -->
     
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Post Details</h4>
                <h2>Single blog post</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>Stand Blog HTML5 Template</span>
                  <h4>Creative HTML Template For Bloggers!</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">

              
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="down-content">
                      <span>{{post.title}}</span>
                      <a href="post-details.html"><h4>{{post.description}}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{post.author}}</a></li>
                        <li><a href="#">{{post.created_time |jalali_date}}</a></li>
                        <li><a href="#">10 Comments</a></li>
                      </ul>
                      <p>You can browse different tags such as <a rel="nofollow" href="https://templatemo.com/tag/multi-page" target="_parent">multi-page</a>, <a rel="nofollow" href="https://templatemo.com/tag/resume" target="_parent">resume</a>, <a rel="nofollow" href="https://templatemo.com/tag/video" target="_parent">video</a>, etc. to see more CSS templates. Sed hendrerit rutrum arcu, non malesuada nisi. Sed id facilisis turpis. Donec justo elit, dapibus vel ultricies in, molestie sit amet risus. In nunc augue, rhoncus sed libero et, tincidunt tempor nisl. Donec egestas, quam eu rutrum ultrices, sapien ante posuere nisl, ac eleifend eros orci vel ante. Pellentesque vitae eleifend velit. Etiam blandit felis sollicitudin vestibulum feugiat.
                      <br><br>Donec tincidunt leo nec magna gravida varius. Suspendisse felis orci, egestas ac sodales quis, venenatis et neque. Vivamus facilisis dignissim arcu et blandit. Maecenas finibus dui non pulvinar lacinia. Ut lacinia finibus lorem vel porttitor. Suspendisse et metus nec libero ultrices varius eget in risus. Cras id nibh at erat pulvinar malesuada et non ipsum. Suspendisse id ipsum leo.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
            
             


                  
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>{{comment.count}} comments</h2>
                    </div>
                    <div class="content">
                      <ul>

                        {% for comment in comment %}
                        <li>
                          <div class="author-thumb">
                            <img src="{%static 'assets/images/comment-author-01.jpg'%}" alt="">
                          </div>
                          <div class="right-content">
                            <h4>{{comment.name}}<span>{{comment.created_time|jalali_date}}</span></h4>
                            <p>{{comment.message}}</p>
                          </div>
                        </li>
                        {% endfor %}
                        {% comment %} <li class="replied">
                          <div class="author-thumb">
                            <img src="{%static 'assets/images/comment-author-02.jpg'%}" alt="">
                          </div>
                          <div class="right-content">
                            <h4>Thirteen Man<span>May 20, 2020</span></h4>
                            <p>In porta urna sed venenatis sollicitudin. Praesent urna sem, pulvinar vel mattis eget.</p>
                          </div>
                        </li> {% endcomment %}
                       
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                      <form id="comment" action="{% url "blog:post-detail" num=post.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">

                          <div class="col-md-6 col-sm-12" style="display:none">
                          <fieldset>
                            <input name="post" value={{post.id}} type="text" id="name" placeholder="Your id" required="">
                          </fieldset>
                        </div>

                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="name" required="">
                            </fieldset>

                          </div>



                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="email" type="text" id="email" placeholder="Your email" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-12 col-sm-12">
                            <fieldset>
                              <input name="subject" type="text" id="subject" placeholder="Subject">
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message" rows="6" id="message" placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>
                          {% comment %} {{form.captcha}} {% endcomment %}
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                {% include "blog/includes/blog-search.html" %} 
                {% include "blog/includes/blog-recent.html" %} 
                {% include "blog/includes/blog-categories.html" %} 
                {% include "blog/includes/blog-tags.html" %} 
              

                
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}