accounts/urls.py
from django.urls import path  
from .views import login_view,logout_view,signup_view,CustomLogin

app_name = 'accounts'  

urlpatterns = [  
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
     path('loginclass/', CustomLogin.as_view(), name='loginclass'),
]

blog/urls.py
from django.urls import path
from .views import blog,post_details

app_name='blog'
urlpatterns = [
    path("",blog ,name='blog'),
    path("<int:num>/",post_details ,name='post-detail'),
    path("category/<cat>/",blog ,name='category'),
    path("tag/<tag>/",blog ,name='tag'),
    path("author/<str:auth>/",blog ,name='author'),
]

core/urls.py

from django.urls import include  
from django.contrib import admin  
from django.urls import path  

from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('', include('website.urls')), 
    path('accounts/',include('accounts.urls')) ,
    path('blog/', include('blog.urls')),  
    path('captcha/', include('captcha.urls')),
]  

# Serve static files in development  
if settings.DEBUG:  
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import Index,about,contact

app_name='website'
urlpatterns = [
    path("",Index,name="index"),
    path("about/",about,name="about"),
    path("contact/",contact,name="contact"),
]

templates/base.html
{% load static %}

<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    
    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css'%}">
 

  </head>

  <body>

    {% include 'message.html' %}


    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'website:index'%}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:about'%}">About Us</a>
              </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog'%}">Blog Entries</a>
              </li> 
        {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post-details'%}">Post Details</a>
              </li> {% endcomment %}



              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:contact'%}">Contact Us</a>
              </li>


        {%if request.user.is_authenticated%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:contact'%}">{{request.user.username}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item" style="display:flex">
                <a class="nav-link" href="{% url 'accounts:signup'%}">Sign-up</a>
                
                <a class="nav-link" href="{% url 'accounts:loginclass'%}">login</a>
                {% comment %} <a class="nav-link" href="{% url 'accounts:login'%}">login</a> {% endcomment %}
              </li>
             
              {%endif%}

            </ul>
          </div>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock content %}


<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="social-icons">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Behance</a></li>
            <li><a href="#">Linkedin</a></li>
            <li><a href="#">Dribbble</a></li>
          </ul>
        </div>
        <div class="col-lg-12">
          <div class="copyright-text">
            <p>Copyright 2020 Stand Blog Co.
                  
               | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Additional Scripts -->
  <script src="{% static 'assets/js/custom.js'%}"></script>
  <script src="{% static 'assets/js/owl.js'%}"></script>
  <script src="{% static 'assets/js/slick.js'%}"></script>
  <script src="{% static 'assets/js/isotope.js'%}"></script>
  <script src="{% static 'assets/js/accordions.js'%}"></script>


  <script language = "text/Javascript"> 
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t){                   //declaring the array outside of the
    if(! cleared[t.id]){                      // function makes it static and global
        cleared[t.id] = 1;  // you could use true and false, but that's more typing
        t.value='';         // with more chance of typos
        t.style.color='#fff';
        }
    }
  </script>

</body>
</html>


templates/message.html
{% load static %}  

<link rel="stylesheet" type="text/css" href="{% static 'vendor/toastify/toastify.css' %}">  
<script src="{% static 'vendor/toastify/toastify.js' %}"></script>  

{% if messages %}  
    {% for message in messages %}  
        <script>  
            Toastify({  
                text: `{{ message|safe }}`,  
                duration: 3000,  
                destination: "https://github.com/apvarun/toastify-js",  
                newWindow: true,  
                close: true,  
                gravity: "top", // `top` or `bottom`  
                position: "right", // `left`, `center` or `right`  
                stopOnFocus: true, // Prevents dismissing of toast on hover  
                style: {  
                    background: "{% if message.tags == 'error' %} #FF5733 {% elif message.tags == 'warning' %} #ffc341  {% else %} linear-gradient(to right, #00b09b, #96c93d) {% endif %}",  
                },  
                onClick: function() {} // Callback after click  
            }).showToast();  
        </script>  
    {% endfor %}  
{% endif %}  

{% if form.errors %}  
<div class="alert alert-error">  
    <h4>Please fix the following errors</h4>  
    <ul>  
        {% for field in form %}  
            {% if field.errors %}  
                {% for error in field.errors %}  
                    <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>  
                {% endfor %}  
            {% endif %}  
        {% endfor %}  
    </ul>  
    {% if form.non_field_errors %}  
        {{ form.non_field_errors }}  
    {% endif %}  
</div>  
{% endif %}